package com.eritv.app;
import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.media3.common.*;import androidx.media3.datasource.DefaultHttpDataSource;import androidx.media3.exoplayer.ExoPlayer;import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;import androidx.media3.ui.PlayerView;
public class MainActivity extends AppCompatActivity{
 static final String STREAM="https://jmc-live.ercdn.net/eritreatv/eritreatv.m3u8";static final long LIMIT=600000,STALL=20000;
 ExoPlayer player;View pill;TextView text;Handler h=new Handler(Looper.getMainLooper());long retryStart=0,lastPos=0,lastAdvance=0;boolean retrying=false;
 final Runnable watch=new Runnable(){public void run(){if(player==null)return;long now=System.currentTimeMillis(),p=player.getCurrentPosition();if(player.isPlaying()&&p>lastPos+500){lastPos=p;lastAdvance=now;clearRetry();}else if(player.getPlayWhenReady()&&lastAdvance>0&&now-lastAdvance>=STALL)retry();h.postDelayed(this,5000);}};
 protected void onCreate(Bundle b){super.onCreate(b);setContentView(com.eritv.app.R.layout.activity_main);pill=findViewById(R.id.retryPill);text=findViewById(R.id.retryText);DefaultHttpDataSource.Factory http=new DefaultHttpDataSource.Factory().setUserAgent("EriTV/1.0 AndroidTV").setAllowCrossProtocolRedirects(true).setConnectTimeoutMs(12000).setReadTimeoutMs(15000);player=new ExoPlayer.Builder(this).setMediaSourceFactory(new DefaultMediaSourceFactory(http)).build();((PlayerView)findViewById(R.id.player)).setPlayer(player);player.addListener(new Player.Listener(){public void onPlayerError(PlaybackException e){retry();}public void onIsPlayingChanged(boolean p){if(p){lastAdvance=System.currentTimeMillis();lastPos=player.getCurrentPosition();clearRetry();}}});play();h.postDelayed(watch,5000);}
 void play(){lastAdvance=System.currentTimeMillis();player.setMediaItem(MediaItem.fromUri(STREAM));player.prepare();player.play();}
 void clearRetry(){if(player!=null&&player.isPlaying()){retrying=false;retryStart=0;pill.setVisibility(View.GONE);}}
 void retry(){long now=System.currentTimeMillis();if(retryStart==0)retryStart=now;if(now-retryStart>=LIMIT){retrying=false;text.setText("Offline");pill.setVisibility(View.VISIBLE);return;}if(retrying)return;retrying=true;text.setText("Reconnecting…");pill.setVisibility(View.VISIBLE);h.postDelayed(()->{if(player==null)return;retrying=false;player.stop();play();h.postDelayed(()->{if(!player.isPlaying())retry();},8000);},3000);}
 protected void onDestroy(){h.removeCallbacksAndMessages(null);if(player!=null)player.release();super.onDestroy();}
}