package com.opentv.app.ui;
import android.content.*;import android.os.*;import android.text.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.recyclerview.widget.*;import com.opentv.app.R;import com.opentv.app.data.*;import com.opentv.app.model.Channel;import java.util.*;import java.util.concurrent.*;
public class MainActivity extends AppCompatActivity{
static final String ALL="https://iptv-org.github.io/iptv/index.category.m3u",CA="https://iptv-org.github.io/iptv/countries/ca.m3u",AB="https://iptv-org.github.io/iptv/subdivisions/ca-ab.m3u",NEWS="https://iptv-org.github.io/iptv/categories/news.m3u",SPORTS="https://iptv-org.github.io/iptv/categories/sports.m3u",MOVIES="https://iptv-org.github.io/iptv/categories/movies.m3u",MUSIC="https://iptv-org.github.io/iptv/categories/music.m3u",KIDS="https://iptv-org.github.io/iptv/categories/kids.m3u",ERITREA="https://iptv-org.github.io/iptv/countries/er.m3u";
final ExecutorService ex=Executors.newSingleThreadExecutor();final Handler main=new Handler(Looper.getMainLooper());final List<Channel>all=new ArrayList<>();FavoritesStore fav;ChannelAdapter adapter;TextView title,count,empty;ProgressBar progress;EditText search;String currentUrl=ALL,currentLabel="All Channels";boolean favoritesMode=false;
protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);fav=new FavoritesStore(this);title=findViewById(R.id.sourceTitle);count=findViewById(R.id.channelCount);empty=findViewById(R.id.emptyText);progress=findViewById(R.id.progress);search=findViewById(R.id.searchBox);
RecyclerView nav=findViewById(R.id.navList);nav.setLayoutManager(new LinearLayoutManager(this));nav.setAdapter(new NavAdapter(Arrays.asList(new NavAdapter.Item("Search",null,false,true),new NavAdapter.Item("All Channels",ALL),new NavAdapter.Item("Canada",CA),new NavAdapter.Item("Alberta",AB),new NavAdapter.Item("Eri TV / Eritrea",ERITREA),new NavAdapter.Item("News",NEWS),new NavAdapter.Item("Sports",SPORTS),new NavAdapter.Item("Movies",MOVIES),new NavAdapter.Item("Music",MUSIC),new NavAdapter.Item("Kids",KIDS),new NavAdapter.Item("Favorites",null,true,false)),i->{if(i.settings){search.requestFocus();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(search,InputMethodManager.SHOW_IMPLICIT);}else if(i.favorites)showFavorites();else load(i.label,i.url);}));
RecyclerView grid=findViewById(R.id.channelGrid);grid.setLayoutManager(new GridLayoutManager(this,5));adapter=new ChannelAdapter(fav,new ChannelAdapter.Listener(){public void onPlay(Channel c){play(c);}public void onFavoriteChanged(Channel c,boolean n){Toast.makeText(MainActivity.this,n?"Added to favorites":"Removed from favorites",Toast.LENGTH_SHORT).show();if(favoritesMode)showFavorites();}});grid.setAdapter(adapter);
RecyclerView cats=findViewById(R.id.categoryList);cats.setLayoutManager(new LinearLayoutManager(this,LinearLayoutManager.HORIZONTAL,false));cats.setAdapter(new CategoryAdapter(c->{}));
search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){filter(s.toString());}public void afterTextChanged(Editable e){}});
findViewById(R.id.retryButton).setOnClickListener(v->{if(favoritesMode)showFavorites();else load(currentLabel,currentUrl);});load(currentLabel,currentUrl);}
void filter(String q){String x=q.trim().toLowerCase(Locale.ROOT);if(x.isEmpty()){adapter.setItems(all);count.setText(all.size()+" channels");return;}List<Channel>out=new ArrayList<>();for(Channel c:all)if(c.name.toLowerCase(Locale.ROOT).contains(x)||c.group.toLowerCase(Locale.ROOT).contains(x)||c.country.toLowerCase(Locale.ROOT).contains(x)||c.language.toLowerCase(Locale.ROOT).contains(x))out.add(c);adapter.setItems(out);count.setText(out.size()+" results");}
void load(String label,String url){favoritesMode=false;currentLabel=label;currentUrl=url;search.setText("");title.setText(label);progress.setVisibility(View.VISIBLE);ex.execute(()->{try{List<Channel>x=new PlaylistRepository(this).load(url,false);main.post(()->{all.clear();all.addAll(x);adapter.setItems(all);count.setText(all.size()+" channels");progress.setVisibility(View.GONE);findViewById(R.id.emptyState).setVisibility(all.isEmpty()?View.VISIBLE:View.GONE);});}catch(Exception e){main.post(()->{progress.setVisibility(View.GONE);findViewById(R.id.emptyState).setVisibility(View.VISIBLE);empty.setText("Could not load playlist\n"+e.getMessage());});}});}
void showFavorites(){favoritesMode=true;currentLabel="Favorites";search.setText("");title.setText(currentLabel);all.clear();all.addAll(fav.all());adapter.setItems(all);count.setText(all.size()+" channels");findViewById(R.id.emptyState).setVisibility(all.isEmpty()?View.VISIBLE:View.GONE);}
void play(Channel c){Intent i=new Intent(this,PlayerActivity.class);i.putExtra("name",c.name);i.putExtra("url",c.url);i.putExtra("logo",c.logo);i.putExtra("group",c.group);i.putExtra("country",c.country);i.putExtra("language",c.language);i.putExtra("playlist_url",favoritesMode?null:currentUrl);i.putExtra("source_label",currentLabel);startActivity(i);}
protected void onResume(){super.onResume();if(favoritesMode)showFavorites();}protected void onDestroy(){ex.shutdownNow();super.onDestroy();}}
