package com.opentv.app.ui;
import android.os.*;import android.view.*;import android.widget.*;import androidx.appcompat.app.AppCompatActivity;import androidx.media3.common.*;import androidx.media3.datasource.DefaultHttpDataSource;import androidx.media3.exoplayer.ExoPlayer;import androidx.media3.exoplayer.DefaultLoadControl;import androidx.media3.exoplayer.source.DefaultMediaSourceFactory;import androidx.media3.ui.PlayerView;import com.opentv.app.R;import com.opentv.app.data.*;import com.opentv.app.model.Channel;import com.opentv.app.util.LogoLoader;import java.util.*;import java.util.concurrent.*;
public class PlayerActivity extends AppCompatActivity{
static final long RETRY_LIMIT=10*60*1000L,STALL_MS=90000L;ExoPlayer player;Channel channel;FavoritesStore fav;TextView name,meta,source,star,zap,retryStatus;ImageView logo;View info,retryPill;final Handler h=new Handler(Looper.getMainLooper());final List<Channel>channels=new ArrayList<>();int index=-1;final ExecutorService ex=Executors.newSingleThreadExecutor();String playlist,label;long retryStart=0,lastPosition=0,lastAdvance=0;boolean retrying=false;
final Runnable watchdog=new Runnable(){public void run(){if(player==null)return;long now=System.currentTimeMillis(),pos=player.getCurrentPosition();boolean playing=player.isPlaying();if(playing&&pos>lastPosition+500){lastPosition=pos;lastAdvance=now;if(retrying||retryStart>0){retrying=false;retryStart=0;retryPill.setVisibility(View.GONE);}}else if(player.getPlaybackState()==Player.STATE_READY&&player.getPlayWhenReady()&&lastAdvance>0&&now-lastAdvance>=STALL_MS){beginRetry("Stream frozen");}h.postDelayed(this,5000);}};
protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_player);fav=new FavoritesStore(this);channel=new Channel("",getIntent().getStringExtra("name"),getIntent().getStringExtra("url"),getIntent().getStringExtra("logo"),getIntent().getStringExtra("group"),getIntent().getStringExtra("country"),getIntent().getStringExtra("language"));playlist=getIntent().getStringExtra("playlist_url");label=getIntent().getStringExtra("source_label");info=findViewById(R.id.playerInfo);name=findViewById(R.id.playerName);meta=findViewById(R.id.playerMeta);source=findViewById(R.id.playerSource);star=findViewById(R.id.playerFavorite);zap=findViewById(R.id.channelZap);retryStatus=findViewById(R.id.retryStatus);retryPill=findViewById(R.id.retryPill);logo=findViewById(R.id.playerLogo);
DefaultHttpDataSource.Factory http=new DefaultHttpDataSource.Factory().setUserAgent("OpenTV/1.2 AndroidTV").setAllowCrossProtocolRedirects(true).setConnectTimeoutMs(12000).setReadTimeoutMs(15000);DefaultLoadControl load=new DefaultLoadControl.Builder().setBufferDurationsMs(15000,120000,5000,10000).setPrioritizeTimeOverSizeThresholds(true).build();player=new ExoPlayer.Builder(this).setMediaSourceFactory(new DefaultMediaSourceFactory(http)).setLoadControl(load).build();((PlayerView)findViewById(R.id.playerView)).setPlayer(player);player.addListener(new Player.Listener(){public void onPlayerError(PlaybackException e){beginRetry("Stream unavailable");}public void onIsPlayingChanged(boolean p){if(p){lastAdvance=System.currentTimeMillis();lastPosition=player.getCurrentPosition();retrying=false;retryStart=0;retryPill.setVisibility(View.GONE);}}});tune(channel);
if(playlist!=null)ex.execute(()->{try{List<Channel>x=new PlaylistRepository(this).load(playlist,false);h.post(()->{channels.addAll(x);for(int i=0;i<x.size();i++)if(x.get(i).url.equals(channel.url))index=i;});}catch(Exception ignored){}});
h.postDelayed(watchdog,5000);}
void tune(Channel c){channel=c;retryStart=0;retrying=false;retryPill.setVisibility(View.GONE);lastPosition=0;lastAdvance=System.currentTimeMillis();name.setText(c.name);meta.setText(c.subtitle());source.setText((label==null?"LIVE TV":label.toUpperCase(Locale.ROOT))+" • LIVE");updateStar();LogoLoader.load(logo,c.logo);player.setMediaItem(MediaItem.fromUri(c.url));player.prepare();player.play();showChannelInfo();}
void beginRetry(String reason){long now=System.currentTimeMillis();if(retryStart==0)retryStart=now;if(now-retryStart>=RETRY_LIMIT){retrying=false;retryStatus.setText("Offline");retryPill.setVisibility(View.VISIBLE);return;}if(retrying)return;retrying=true;retryStatus.setText("Reconnecting…");retryPill.setVisibility(View.VISIBLE);h.postDelayed(()->{if(player==null)return;retrying=false;if(System.currentTimeMillis()-retryStart>=RETRY_LIMIT){beginRetry(reason);return;}player.stop();player.setMediaItem(MediaItem.fromUri(channel.url));player.prepare();player.play();h.postDelayed(()->{if(!player.isPlaying())beginRetry(reason);},8000);},3000);}
void showChannelInfo(){info.setVisibility(View.VISIBLE);h.removeCallbacks(hideInfo);h.postDelayed(hideInfo,3000);}final Runnable hideInfo=()->info.setVisibility(View.GONE);void toggleFavorite(){boolean n=fav.toggle(channel);updateStar();Toast.makeText(this,n?"Added to favorites":"Removed from favorites",Toast.LENGTH_SHORT).show();}
void updateStar(){star.setText(fav.contains(channel.url)?"★ FAVORITE":"☆ FAVORITE");}
void change(int d){if(channels.isEmpty())return;if(index<0)index=0;index=(index+d+channels.size())%channels.size();tune(channels.get(index));zap.setText(channel.name);zap.setVisibility(View.VISIBLE);h.postDelayed(()->zap.setVisibility(View.GONE),1500);}
public boolean onKeyDown(int k,KeyEvent e){if(e.getRepeatCount()>0)return true;if(k==KeyEvent.KEYCODE_DPAD_UP||k==KeyEvent.KEYCODE_CHANNEL_UP){change(-1);return true;}if(k==KeyEvent.KEYCODE_DPAD_DOWN||k==KeyEvent.KEYCODE_CHANNEL_DOWN){change(1);return true;}if(k==KeyEvent.KEYCODE_DPAD_CENTER||k==KeyEvent.KEYCODE_ENTER){toggleFavorite();return true;}if(k==KeyEvent.KEYCODE_INFO||k==KeyEvent.KEYCODE_MENU){showChannelInfo();return true;}return super.onKeyDown(k,e);}
protected void onDestroy(){h.removeCallbacksAndMessages(null);ex.shutdownNow();if(player!=null)player.release();super.onDestroy();}}
